[project]
name = "SC_TSL_15092024_Plate_Detect"
version = "0.1.0"
description = "SC_TSL_15092024_Plate_Detect"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[tool.flit.module]
name = "src"

[tool.flit.sdist]
include = ["src/", "lib/"]

